/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\cute_pizza.glb 
Author: cornsoup (https://sketchfab.com/cornsoup)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cute-pizza-26th-may-2020-654d6638fab245ef814ca21bee970f2f
Title: cute pizza 26th May 2020
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/cute_pizza.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_3.geometry} material={materials.material_7} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.material_6} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.material_5} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.material_4} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.material_3} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.material_2} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.material_2} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.material_1} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.material_1} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.material_0} />
      </group>
    </group>
  )
}

useGLTF.preload('/cute_pizza.glb')
