/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\scene.gltf 
Author: Ehsan Abbasi (https://sketchfab.com/EhsanAbbasi)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/back-yard-burgers-classic-burger-6e13942ff76d4129b06e097cdd060adb
Title: Back Yard Burgers - Classic Burger
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export function Model(props) {
  const { nodes, materials } = useGLTF('../scene.gltf')


  const positionRef = useRef();

  useFrame((state) => {
     positionRef.current.rotation.y = state.clock.getElapsedTime() * 0.55;
  })
  return (
    <group ref={positionRef} {...props} dispose={null}>
      <group position={[0, -9.485, 1.575]} rotation={[Math.PI / 2, 0, 0]}>
        <group rotation={[-Math.PI, 0, 0]}>
          <group position={[0.055, 0.788, 5.9]}>
            <group position={[-0.193, -0.219, -6.774]} rotation={[-2.142, -0.11, -1.426]} scale={[1.165, 1.452, 1.552]}>
              <mesh geometry={nodes.Bread2B_Bread2A_0.geometry} material={materials.Bread2A} position={[-1.899, 0.749, -8.544]} />
            </group>
            <group position={[-5.785, 4.345, -0.526]} rotation={[0.018, 0.009, 3.004]} scale={0.646}>
              <mesh geometry={nodes.Tomato003_TomatoA_0.geometry} material={materials.TomatoA} />
              <mesh geometry={nodes.Tomato003_Tomato_0.geometry} material={materials.Tomato} />
            </group>
            <group position={[2.689, -3.618, -0.576]} rotation={[-0.009, 0.06, -2.914]} scale={0.896}>
              <mesh geometry={nodes.Tomato2A_TomatoA_0.geometry} material={materials.TomatoA} />
              <mesh geometry={nodes.Tomato2A_Tomato_0.geometry} material={materials.Tomato} />
            </group>
            <group position={[0.359, -0.722, 2.79]} rotation={[0.183, 0.915, 0]} scale={[1.393, 1.472, 1.529]}>
              <mesh geometry={nodes.Bread2A_Bread2A_0.geometry} material={materials.Bread2A} position={[-1.899, 0.749, -8.544]} />
            </group>
            <group position={[0.355, -0.429, -3.93]} rotation={[0, 0, -1.309]} scale={1.009}>
              <mesh geometry={nodes.Patty2_PattyA_0.geometry} material={materials.PattyA} />
              <mesh geometry={nodes.Patty2_PattyB_0.geometry} material={materials.PattyB} />
            </group>
            <group position={[0.559, -0.448, 0.266]} rotation={[2.419, -1.245, -1.139]} scale={2.664}>
              <mesh geometry={nodes.Cabbage2_Cabbage2_0.geometry} material={materials.Cabbage2} position={[1.221, 20.551, -0.247]} />
            </group>
            <mesh geometry={nodes.Cheese2_Cheese_0.geometry} material={materials.Cheese} position={[0.084, -0.837, -1.27]} rotation={[0, 0, -1.309]} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('../scene.gltf')
